### ISSUE TITLE
Connection with Depop Mass Listing Tool

### ISSUE THREAD

**Issue by matthall8** [matthall8/sgmcr#10]
Then maybe a different spreadsheet which duplicates and changed the data to fit depop mass lister, if you go onto Google drive you’ll see the document I use for mass lister as an example

**Comment by matthall8** [comment]
Working through this now. A few things to discuss:

'Product Category' -> We need to agree on a list of the product cateogries we will use and the terms you will use. Also, need to discuss how we will treat Men Vs Women clothes.

'Price' -> Do you want to fill it in on the description generator or do you want it to generate blank and you fill it in later?

'Brands' -> As Product Category. Also some brands we sell are not listed e.g. CP Company. What do we do for those?

'Condition' -> We need to agree on a list of the conditions you will use to make sure it matches

'Colour' -> We need to agree on a list of the colours you will use. Also, need to decide if we will ever need to list with two colours and how we will approach that.

'Source' -> Assuming it's either always 'designer', 'vintage' or 'preloved'. How do you want this filling in?

'Age' - >Assuming it's always modern

'Style' -> Always streetwear & casual?

'Location' -> Always UK

'Domestic Shipping Prices -> 3.49 is it?

'International Shipping Prices -> 19.99?

**Comment by matthall8** [comment]
This has been done as agreed - see: https://docs.google.com/spreadsheets/d/1Afq13vxeRAAX4vODYhYpIieEilWEbe001fNzjb7kUeo/edit?usp=sharing

**Comment by streetgarms** [comment]
Spot on - Thanks a lot bro :)
