### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by matthall8** [matthall8/sgmcr#11]
Maybe a separate row which replaces ‘Lightly worn!’with the data in it for example small hole on chest as shown in pictures

**Comment by matthall8** [comment]
@streetgarms  - I've added a new column for additional condition comments (G). If the column is empty it will be just say 'No rips, holes or stains' in the description. If it is filled in it will say whatever is in column G instead.

See Row 3 for an example of what happens if you fill it in vs Row 2 if you don't - https://docs.google.com/spreadsheets/d/1yylqTViLdTsDNT-saICd-YeTrD1O2EoR_PgxSkAlvFo/edit?usp=sharing 

Please can you check you're happy with it and close the issue if so.

**Comment by streetgarms** [comment]
Working
