### ISSUE TITLE
SKU

### ISSUE THREAD

**Issue by matthall8** [matthall8/sgmcr#12]
Then also have a spreadsheet which uses the new function I added in as well as the other data to build sku a bit quicker

**Comment by matthall8** [comment]
@streetgarms - I have updated the column K in the 'Description Generator' tab on the new Lisitng Tool - https://docs.google.com/spreadsheets/d/1yylqTViLdTsDNT-saICd-YeTrD1O2EoR_PgxSkAlvFo/edit?usp=sharing. 

Please can you check you're happy with it and close the issue if so.

**Comment by streetgarms** [comment]
Great
