### ISSUE TITLE
Manually spaces

### ISSUE THREAD

**Issue by matthall8** [matthall8/sgmcr#13]
Things like stone island hoodies which don’t have a set data such as supreme hands Tshirt I’m mansuslly having to remove the space, maybe split across all of product types and brands across a mother spreadsheet

**Comment by matthall8** [comment]
@streetgarms - I'm not quite sure what you mean by this one. Please could you populate Row 3 of https://docs.google.com/spreadsheets/d/1yylqTViLdTsDNT-saICd-YeTrD1O2EoR_PgxSkAlvFo/edit#gid=1557446601 with an example?

**Comment by streetgarms** [comment]
Working :)
